### PR TITLE
Install Python bits

### PR DESCRIPTION
**Pull request by zerebubuth**
This fixes the autotools stuff so that it installs the Python extensions in the correct directory. It also installs the worker script in the `bin` directory and other Python scripts/libraries in the correct `site-packages` directory.

### CODE REVIEW

**Comment by zerebubuth** [comment]
cc @charterchap @pnorman

**Comment by pnorman** [comment]
Looks okay. Well, as much as recursive make ever looks okay.

**Comment by zerebubuth** [comment]
Yeah. The recursive make is only because I couldn't figure out how to strip the leading `py/` from the names of all the Python scripts. But I wonder now if that's not important, given that another part of the issue was that it wasn't respecting the directories... I'll see if I can merge the other `Makefile.am` back in, as I'd prefer it non-recursive too.

**Comment by charterchap** [comment]
I'm trying to test it out with make install DESTDIR= and I get errors (unrelated to this change set). Have you been able to run it all the through?

**Comment by zerebubuth** [comment]
@charterchap Yup, it works for me... Here's the config/make likes I've been using on lm15. What was the error you got from `make install`?

    ./autogen.sh && ./configure --prefix=/data/mapquest/burritile --with-boost=/data/mapquest/stdbase_devtools --with-mapnik-config=/data/mapquest/stdbase_devtools/bin/mapnik-config --with-protoc=/data/mapquest/stdbase_devtools/bin/protoc --with-bz2=/data/mapquest/stdbase_devtools --with-libuuid=/data/mapquest/stdbase_devtools --with-gdal=/data/mapquest/stdbase_devtools/bin/gdal-config CXXFLAGS="-DBOOST_MPL_CFG_NO_PREPROCESSED_HEADERS -DBOOST_MPL_LIMIT_VECTOR_SIZE=30 -DBOOST_MPL_LIMIT_MAP_SIZE=30 -Wno-unused-but-set-variable -Wno-unused-local-typedefs -Wno-unused-variable" PKG_CONFIG_PATH=/data/mapquest/stdbase_devtools/lib/pkgconfig PYTHON_VERSION=2.6 PYTHON=/data/mapquest/stdbase_devtools/bin/python GDLIB_CONFIG=/data/mapquest/stdbase_devtools/bin/gdlib-config
    make clean && make -j 12 && rm -rf install && mkdir install && make install DESTDIR=$PWD/install

**Comment by charterchap** [comment]
@zerebubuth let me try a clean build with those params. make install gives errors on ld: 
`collect2: error: ld returned 1 exit status`
`libtool: install: error: relink `libburritile_coverage.la' with the above command before installing it`
Which I can make go away by adding a -L./.libs to g++.

**Comment by zerebubuth** [comment]
@charterchap I thought I fixed that with fe3373d :worried: Are you running make with any `-j` parallel arguments?

**Comment by charterchap** [comment]
Well, that worked. I only did a make clean and configure after some of the changes... I'm guessing that was it. I can confirm now that I see the file in install/data/mapquest/burritile/lib/python2.6/site-packages/burritile and the bin dir.

**Comment by zerebubuth** [comment]
Seems related to (this bug)[http://debbugs.gnu.org/cgi/bugreport.cgi?bug=7328] - apparently it's a (known issue)[http://lists.gnu.org/archive/html/automake/2010-03/msg00039.html] for which the work-around is to explicitly specify the dependencies as different install targets. I'll add this as a separate issue/bug and we can address it later.

**Comment by pnorman** [comment]
cross-ref #26

**Pull request merged**
